name: cfsan2snp2
owner: galaxytrakr
description: CSP2 is a tool for identifying single nucleotide polymorphisms (SNPs) in bacterial genomes.
long_description: |-
  CSP2 is a tool for identifying single nucleotide polymorphisms (SNPs) in bacterial genomes.
homepage_url: https://github.com/CFSAN-Biostatistics/CSP2
build_source_url: https://github.com/CFSAN-Biostatistics/CSP2.git
build_source_version: v.0.9.7.7
type: unrestricted
categories:
  - "Test"